# config/packages/knp_paginator.yaml
knp_paginator:
    default_options:
        # Limite par défaut des éléments par page
        default_limit: 3
        # Nom du paramètre de la page dans l'URL
        page_name: page
        # Nom du champ pour le tri
        sort_field_name: sort
        # Nom de la direction du tri
        sort_direction_name: direction
    template:
        # Choix du template pour la pagination (par exemple, avec Bootstrap v5)
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
        # Autres options valides pour le template
        sortable: true
        rel_links: true
