liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~

        product_image:
            quality: 85
            filters:
                thumbnail:
                    size: [300, 300]  # Redimensionner à 300x300 px
                    mode: outbound     # Mode outbound : remplissage strict
