monolog:
    channels:
        - deprecation
        - liip_imagine
        - mailer

    handlers:
        # Gestion des logs en développement
        when@dev:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]

        # Gestion des logs en console
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]

        # Gestion des logs en test
        when@test:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]

        # Gestion des logs en production
        when@prod:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]

        # Handler spécifique pour Liip Imagine
        liip_imagine:
            type: stream
            path: '%kernel.logs_dir%/liip_imagine.log'
            level: debug
            channels: ['liip_imagine']

        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        mailer:
            type: stream
            path: "%kernel.logs_dir%/mailer.log"
            level: debug
            channels: ["mailer"]










