controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

commande:
    resource: ../src/Commande/Controller/
    type: annotation

produit:
    resource: ../src/Produit/Controller/
    type: annotation
