# config/services.yaml
parameters:
    images_events_directory: '%kernel.project_dir%/assets/ImagesEvents'
    attachments_directory: '%kernel.project_dir%/assets/ImagesReclamations'
    partners_directory: '%kernel.project_dir%/public/uploads/partners'
    twilio_account_sid: '%env(TWILIO_ACCOUNT_SID)%'
    twilio_auth_token: '%env(TWILIO_AUTH_TOKEN)%'
    twilio_phone_number: '%env(TWILIO_PHONE_NUMBER)%'
    app.upload_directory: '%kernel.project_dir%/public/uploads/posts'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
        bind:
            $uploadDirectory: '%app.upload_directory%'

    App\Controller\ForumController:
        arguments:
            $uploadDirectory: '%app.upload_directory%'

    App\Service\TwilioService:
        arguments:
            $sid: '%twilio_account_sid%'
            $token: '%twilio_auth_token%'
            $from: '%twilio_phone_number%'